language: php
sudo: false
php:
  - 5.6
  - 7.1
  - 7.2
  - hhvm
after_success:
  - test -z $COVERALLS || (composer require satooshi/php-coveralls && vendor/bin/coveralls -v)
matrix:
  include:
    - php: 5.6
      env: COVERALLS=true
  allow_failures:
    - php: hhvm
